server:
  port: 9100 # 伺服器的port號

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # h2 database 連接位址
    initialize: false
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: 12345 # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
